server:
  port: 27001
spring:
  redis:
    port: 6379
    password: 123456
    database: 0
    host: 192.168.40.46
    lettuce:
      pool:
        max-active: 10
        min-idle: 10
        max-wait: 300d
    timeout: 2000
